/* automatically generated by rust-bindgen */

#[doc(hidden)]

#[allow(non_snake_case, non_camel_case_types, non_upper_case_globals)]
pub mod root {
    #[allow(unused_imports)]
    use self::super::root;
    /// The public interface to Libaudioverse.
    pub type LavError = ::std::os::raw::c_int;
    pub type LavHandle = ::std::os::raw::c_int;
    pub type LavParameterlessCallback = ::std::option::Option<
        unsafe extern "C" fn(nodeHandle: root::LavHandle, userdata: *mut ::std::os::raw::c_void),
    >;
    pub type LavTimeCallback = ::std::option::Option<
        unsafe extern "C" fn(
            handle: root::LavHandle,
            time: f64,
            userdata: *mut ::std::os::raw::c_void,
        ),
    >;
    pub const Lav_ERRORS_Lav_ERROR_NONE: root::Lav_ERRORS = 0;
    pub const Lav_ERRORS_Lav_ERROR_UNKNOWN: root::Lav_ERRORS = 1;
    pub const Lav_ERRORS_Lav_ERROR_NOT_INITIALIZED: root::Lav_ERRORS = 2;
    pub const Lav_ERRORS_Lav_ERROR_TYPE_MISMATCH: root::Lav_ERRORS = 3;
    pub const Lav_ERRORS_Lav_ERROR_INVALID_PROPERTY: root::Lav_ERRORS = 4;
    pub const Lav_ERRORS_Lav_ERROR_NULL_POINTER: root::Lav_ERRORS = 5;
    pub const Lav_ERRORS_Lav_ERROR_MEMORY: root::Lav_ERRORS = 6;
    pub const Lav_ERRORS_Lav_ERROR_INVALID_POINTER: root::Lav_ERRORS = 7;
    pub const Lav_ERRORS_Lav_ERROR_INVALID_HANDLE: root::Lav_ERRORS = 8;
    pub const Lav_ERRORS_Lav_ERROR_RANGE: root::Lav_ERRORS = 9;
    pub const Lav_ERRORS_Lav_ERROR_CANNOT_INIT_AUDIO: root::Lav_ERRORS = 10;
    pub const Lav_ERRORS_Lav_ERROR_NO_SUCH_DEVICE: root::Lav_ERRORS = 11;
    pub const Lav_ERRORS_Lav_ERROR_FILE: root::Lav_ERRORS = 12;
    pub const Lav_ERRORS_Lav_ERROR_FILE_NOT_FOUND: root::Lav_ERRORS = 13;
    pub const Lav_ERRORS_Lav_ERROR_HRTF_INVALID: root::Lav_ERRORS = 14;
    pub const Lav_ERRORS_Lav_ERROR_CANNOT_CROSS_SERVERS: root::Lav_ERRORS = 15;
    pub const Lav_ERRORS_Lav_ERROR_CAUSES_CYCLE: root::Lav_ERRORS = 16;
    pub const Lav_ERRORS_Lav_ERROR_PROPERTY_IS_READ_ONLY: root::Lav_ERRORS = 17;
    pub const Lav_ERRORS_Lav_ERROR_OVERLAPPING_AUTOMATORS: root::Lav_ERRORS = 18;
    pub const Lav_ERRORS_Lav_ERROR_CANNOT_CONNECT_TO_PROPERTY: root::Lav_ERRORS = 19;
    pub const Lav_ERRORS_Lav_ERROR_BUFFER_IN_USE: root::Lav_ERRORS = 20;
    pub const Lav_ERRORS_Lav_ERROR_INTERNAL: root::Lav_ERRORS = 999;
    pub type Lav_ERRORS = i32;
    pub const Lav_PROPERTY_TYPES_Lav_PROPERTYTYPE_INT: root::Lav_PROPERTY_TYPES = 0;
    pub const Lav_PROPERTY_TYPES_Lav_PROPERTYTYPE_FLOAT: root::Lav_PROPERTY_TYPES = 1;
    pub const Lav_PROPERTY_TYPES_Lav_PROPERTYTYPE_DOUBLE: root::Lav_PROPERTY_TYPES = 2;
    pub const Lav_PROPERTY_TYPES_Lav_PROPERTYTYPE_STRING: root::Lav_PROPERTY_TYPES = 3;
    pub const Lav_PROPERTY_TYPES_Lav_PROPERTYTYPE_FLOAT3: root::Lav_PROPERTY_TYPES = 4;
    pub const Lav_PROPERTY_TYPES_Lav_PROPERTYTYPE_FLOAT6: root::Lav_PROPERTY_TYPES = 5;
    pub const Lav_PROPERTY_TYPES_Lav_PROPERTYTYPE_FLOAT_ARRAY: root::Lav_PROPERTY_TYPES = 6;
    pub const Lav_PROPERTY_TYPES_Lav_PROPERTYTYPE_INT_ARRAY: root::Lav_PROPERTY_TYPES = 7;
    pub const Lav_PROPERTY_TYPES_Lav_PROPERTYTYPE_BUFFER: root::Lav_PROPERTY_TYPES = 8;
    pub type Lav_PROPERTY_TYPES = i32;
    pub const Lav_OBJECT_TYPES_Lav_OBJTYPE_SERVER: root::Lav_OBJECT_TYPES = 0;
    pub const Lav_OBJECT_TYPES_Lav_OBJTYPE_BUFFER: root::Lav_OBJECT_TYPES = 1;
    pub const Lav_OBJECT_TYPES_Lav_OBJTYPE_GENERIC_NODE: root::Lav_OBJECT_TYPES = 2;
    pub const Lav_OBJECT_TYPES_Lav_OBJTYPE_ENVIRONMENT_NODE: root::Lav_OBJECT_TYPES = 3;
    pub const Lav_OBJECT_TYPES_Lav_OBJTYPE_SOURCE_NODE: root::Lav_OBJECT_TYPES = 4;
    pub const Lav_OBJECT_TYPES_Lav_OBJTYPE_HRTF_NODE: root::Lav_OBJECT_TYPES = 5;
    pub const Lav_OBJECT_TYPES_Lav_OBJTYPE_SINE_NODE: root::Lav_OBJECT_TYPES = 6;
    pub const Lav_OBJECT_TYPES_Lav_OBJTYPE_HARD_LIMITER_NODE: root::Lav_OBJECT_TYPES = 7;
    pub const Lav_OBJECT_TYPES_Lav_OBJTYPE_CROSSFADING_DELAY_NODE: root::Lav_OBJECT_TYPES = 8;
    pub const Lav_OBJECT_TYPES_Lav_OBJTYPE_DOPPLERING_DELAY_NODE: root::Lav_OBJECT_TYPES = 9;
    pub const Lav_OBJECT_TYPES_Lav_OBJTYPE_AMPLITUDE_PANNER_NODE: root::Lav_OBJECT_TYPES = 10;
    pub const Lav_OBJECT_TYPES_Lav_OBJTYPE_PUSH_NODE: root::Lav_OBJECT_TYPES = 11;
    pub const Lav_OBJECT_TYPES_Lav_OBJTYPE_BIQUAD_NODE: root::Lav_OBJECT_TYPES = 12;
    pub const Lav_OBJECT_TYPES_Lav_OBJTYPE_PULL_NODE: root::Lav_OBJECT_TYPES = 13;
    pub const Lav_OBJECT_TYPES_Lav_OBJTYPE_GRAPH_LISTENER_NODE: root::Lav_OBJECT_TYPES = 14;
    pub const Lav_OBJECT_TYPES_Lav_OBJTYPE_RINGMOD_NODE: root::Lav_OBJECT_TYPES = 15;
    pub const Lav_OBJECT_TYPES_Lav_OBJTYPE_MULTIPANNER_NODE: root::Lav_OBJECT_TYPES = 16;
    pub const Lav_OBJECT_TYPES_Lav_OBJTYPE_FEEDBACK_DELAY_NETWORK_NODE: root::Lav_OBJECT_TYPES = 17;
    pub const Lav_OBJECT_TYPES_Lav_OBJTYPE_ADDITIVE_SQUARE_NODE: root::Lav_OBJECT_TYPES = 18;
    pub const Lav_OBJECT_TYPES_Lav_OBJTYPE_ADDITIVE_TRIANGLE_NODE: root::Lav_OBJECT_TYPES = 19;
    pub const Lav_OBJECT_TYPES_Lav_OBJTYPE_ADDITIVE_SAW_NODE: root::Lav_OBJECT_TYPES = 20;
    pub const Lav_OBJECT_TYPES_Lav_OBJTYPE_NOISE_NODE: root::Lav_OBJECT_TYPES = 21;
    pub const Lav_OBJECT_TYPES_Lav_OBJTYPE_IIR_NODE: root::Lav_OBJECT_TYPES = 22;
    pub const Lav_OBJECT_TYPES_Lav_OBJTYPE_GAIN_NODE: root::Lav_OBJECT_TYPES = 23;
    pub const Lav_OBJECT_TYPES_Lav_OBJTYPE_CHANNEL_SPLITTER_NODE: root::Lav_OBJECT_TYPES = 24;
    pub const Lav_OBJECT_TYPES_Lav_OBJTYPE_CHANNEL_MERGER_NODE: root::Lav_OBJECT_TYPES = 25;
    pub const Lav_OBJECT_TYPES_Lav_OBJTYPE_BUFFER_NODE: root::Lav_OBJECT_TYPES = 26;
    pub const Lav_OBJECT_TYPES_Lav_OBJTYPE_BUFFER_TIMELINE_NODE: root::Lav_OBJECT_TYPES = 27;
    pub const Lav_OBJECT_TYPES_Lav_OBJTYPE_RECORDER_NODE: root::Lav_OBJECT_TYPES = 28;
    pub const Lav_OBJECT_TYPES_Lav_OBJTYPE_CONVOLVER_NODE: root::Lav_OBJECT_TYPES = 29;
    pub const Lav_OBJECT_TYPES_Lav_OBJTYPE_FFT_CONVOLVER_NODE: root::Lav_OBJECT_TYPES = 30;
    pub const Lav_OBJECT_TYPES_Lav_OBJTYPE_THREE_BAND_EQ_NODE: root::Lav_OBJECT_TYPES = 31;
    pub const Lav_OBJECT_TYPES_Lav_OBJTYPE_FILTERED_DELAY_NODE: root::Lav_OBJECT_TYPES = 32;
    pub const Lav_OBJECT_TYPES_Lav_OBJTYPE_CROSSFADER_NODE: root::Lav_OBJECT_TYPES = 33;
    pub const Lav_OBJECT_TYPES_Lav_OBJTYPE_ONE_POLE_FILTER_NODE: root::Lav_OBJECT_TYPES = 34;
    pub const Lav_OBJECT_TYPES_Lav_OBJTYPE_FIRST_ORDER_FILTER_NODE: root::Lav_OBJECT_TYPES = 35;
    pub const Lav_OBJECT_TYPES_Lav_OBJTYPE_ALLPASS_NODE: root::Lav_OBJECT_TYPES = 36;
    pub const Lav_OBJECT_TYPES_Lav_OBJTYPE_FDN_REVERB_NODE: root::Lav_OBJECT_TYPES = 37;
    pub const Lav_OBJECT_TYPES_Lav_OBJTYPE_BLIT_NODE: root::Lav_OBJECT_TYPES = 38;
    pub const Lav_OBJECT_TYPES_Lav_OBJTYPE_DC_BLOCKER_NODE: root::Lav_OBJECT_TYPES = 39;
    pub const Lav_OBJECT_TYPES_Lav_OBJTYPE_LEAKY_INTEGRATOR_NODE: root::Lav_OBJECT_TYPES = 40;
    pub const Lav_OBJECT_TYPES_Lav_OBJTYPE_FILE_STREAMER_NODE: root::Lav_OBJECT_TYPES = 41;
    pub type Lav_OBJECT_TYPES = i32;
    pub const Lav_NODE_STATES_Lav_NODESTATE_PAUSED: root::Lav_NODE_STATES = 0;
    pub const Lav_NODE_STATES_Lav_NODESTATE_PLAYING: root::Lav_NODE_STATES = 1;
    pub const Lav_NODE_STATES_Lav_NODESTATE_ALWAYS_PLAYING: root::Lav_NODE_STATES = 2;
    /// Node states.
    pub type Lav_NODE_STATES = i32;
    pub const Lav_LOGGING_LEVELS_Lav_LOGGING_LEVEL_CRITICAL: root::Lav_LOGGING_LEVELS = 10;
    pub const Lav_LOGGING_LEVELS_Lav_LOGGING_LEVEL_INFO: root::Lav_LOGGING_LEVELS = 20;
    pub const Lav_LOGGING_LEVELS_Lav_LOGGING_LEVEL_DEBUG: root::Lav_LOGGING_LEVELS = 30;
    pub const Lav_LOGGING_LEVELS_Lav_LOGGING_LEVEL_OFF: root::Lav_LOGGING_LEVELS = 40;
    /// Logging levels.
    pub type Lav_LOGGING_LEVELS = i32;
    extern "C" {
        /// Initialize Libaudioverse.
        pub fn Lav_initialize() -> root::LavError;
    }
    extern "C" {
        /// Shuts down the library.
        ///
        /// After a call to this function, any Libaudioverse handles are invalid.
        /// So too are any pointers that Libaudioverse gave you, of any form.
        pub fn Lav_shutdown() -> root::LavError;
    }
    extern "C" {
        pub fn Lav_isInitialized(destination: *mut ::std::os::raw::c_int) -> root::LavError;
    }
    extern "C" {
        /// Query the thread's current error.
        /// Pointers are valid until the next time an error happens on this thread.
        pub fn Lav_errorGetMessage(
            destination: *mut *const ::std::os::raw::c_char,
        ) -> root::LavError;
    }
    extern "C" {
        pub fn Lav_errorGetFile(destination: *mut *const ::std::os::raw::c_char) -> root::LavError;
    }
    extern "C" {
        pub fn Lav_errorGetLine(destination: *mut ::std::os::raw::c_int) -> root::LavError;
    }
    extern "C" {
        /// Free any pointer that libaudioverse gives you.  If something goes wrong, namely that the pointer isn't from Libaudioverse in the first place, this tries to fail gracefully and give you an error, but don't rely on this.
        pub fn Lav_free(ptr: *mut ::std::os::raw::c_void) -> root::LavError;
    }
    extern "C" {
        /// Handle refcounts.
        pub fn Lav_handleIncRef(handle: root::LavHandle) -> root::LavError;
    }
    extern "C" {
        pub fn Lav_handleDecRef(handle: root::LavHandle) -> root::LavError;
    }
    extern "C" {
        /// Every handle has a first external access bit which is cleared by this function.
        /// This is to avoid an issue with bindings that need to know if they should increment counts.
        pub fn Lav_handleGetAndClearFirstAccess(
            handle: root::LavHandle,
            destination: *mut ::std::os::raw::c_int,
        ) -> root::LavError;
    }
    extern "C" {
        pub fn Lav_handleGetRefCount(
            handle: root::LavHandle,
            destination: *mut ::std::os::raw::c_int,
        ) -> root::LavError;
    }
    extern "C" {
        pub fn Lav_handleGetType(
            handle: root::LavHandle,
            destination: *mut ::std::os::raw::c_int,
        ) -> root::LavError;
    }
    /// Configure and query logging.
    ///
    /// These functions may be used before library initialization, the intent being that you can get initialization logs.  These functions, like all other functions, cannot be used after library termination.
    pub type LavLoggingCallback = ::std::option::Option<
        unsafe extern "C" fn(level: ::std::os::raw::c_int, message: *const ::std::os::raw::c_char),
    >;
    extern "C" {
        pub fn Lav_setLoggingCallback(cb: root::LavLoggingCallback) -> root::LavError;
    }
    extern "C" {
        pub fn Lav_getLoggingCallback(destination: *mut root::LavLoggingCallback)
            -> root::LavError;
    }
    extern "C" {
        pub fn Lav_setLoggingLevel(level: ::std::os::raw::c_int) -> root::LavError;
    }
    extern "C" {
        pub fn Lav_getLoggingLevel(destination: *mut ::std::os::raw::c_int) -> root::LavError;
    }
    /// Configure the handle destroyed callback.  Also may be used before initialization.
    /// This exists only for bindings.  If you use this in your C program, you may have design issues.
    pub type LavHandleDestroyedCallback =
        ::std::option::Option<unsafe extern "C" fn(which: root::LavHandle)>;
    extern "C" {
        pub fn Lav_setHandleDestroyedCallback(
            cb: root::LavHandleDestroyedCallback,
        ) -> root::LavError;
    }
    extern "C" {
        pub fn Lav_deviceGetCount(destination: *mut ::std::os::raw::c_uint) -> root::LavError;
    }
    extern "C" {
        pub fn Lav_deviceGetName(
            index: ::std::os::raw::c_uint,
            destination: *mut *mut ::std::os::raw::c_char,
        ) -> root::LavError;
    }
    extern "C" {
        pub fn Lav_deviceGetIdentifierString(
            index: ::std::os::raw::c_uint,
            destination: *mut *mut ::std::os::raw::c_char,
        ) -> root::LavError;
    }
    extern "C" {
        pub fn Lav_deviceGetChannels(
            index: ::std::os::raw::c_uint,
            destination: *mut ::std::os::raw::c_uint,
        ) -> root::LavError;
    }
    extern "C" {
        pub fn Lav_createServer(
            sr: ::std::os::raw::c_uint,
            blockSize: ::std::os::raw::c_uint,
            destination: *mut root::LavHandle,
        ) -> root::LavError;
    }
    extern "C" {
        pub fn Lav_serverGetBlockSize(
            serverHandle: root::LavHandle,
            destination: *mut ::std::os::raw::c_int,
        ) -> root::LavError;
    }
    extern "C" {
        pub fn Lav_serverGetBlock(
            serverHandle: root::LavHandle,
            channels: ::std::os::raw::c_uint,
            mayApplyMixingMatrix: ::std::os::raw::c_int,
            buffer: *mut f32,
        ) -> root::LavError;
    }
    extern "C" {
        pub fn Lav_serverGetSr(
            serverHandle: root::LavHandle,
            destination: *mut ::std::os::raw::c_int,
        ) -> root::LavError;
    }
    extern "C" {
        /// Set or clear the output device.
        pub fn Lav_serverSetOutputDevice(
            serverHandle: root::LavHandle,
            device: *const ::std::os::raw::c_char,
            channels: ::std::os::raw::c_int,
            mixahead: ::std::os::raw::c_int,
        ) -> root::LavError;
    }
    extern "C" {
        pub fn Lav_serverClearOutputDevice(serverHandle: root::LavHandle) -> root::LavError;
    }
    extern "C" {
        pub fn Lav_serverLock(serverHandle: root::LavHandle) -> root::LavError;
    }
    extern "C" {
        pub fn Lav_serverUnlock(serverHandle: root::LavHandle) -> root::LavError;
    }
    extern "C" {
        pub fn Lav_serverSetBlockCallback(
            serverHandle: root::LavHandle,
            callback: root::LavTimeCallback,
            userdata: *mut ::std::os::raw::c_void,
        ) -> root::LavError;
    }
    extern "C" {
        pub fn Lav_serverWriteFile(
            serverHandle: root::LavHandle,
            path: *const ::std::os::raw::c_char,
            channels: ::std::os::raw::c_int,
            duration: f64,
            mayApplyMixingMatrix: ::std::os::raw::c_int,
        ) -> root::LavError;
    }
    extern "C" {
        pub fn Lav_serverSetThreads(
            serverHandle: root::LavHandle,
            threads: ::std::os::raw::c_int,
        ) -> root::LavError;
    }
    extern "C" {
        pub fn Lav_serverGetThreads(
            serverHandle: root::LavHandle,
            destination: *mut ::std::os::raw::c_int,
        ) -> root::LavError;
    }
    extern "C" {
        pub fn Lav_serverCallIn(
            serverHandle: root::LavHandle,
            when: f64,
            inAudioThread: ::std::os::raw::c_int,
            cb: root::LavTimeCallback,
            userdata: *mut ::std::os::raw::c_void,
        ) -> root::LavError;
    }
    extern "C" {
        /// Buffers.
        /// Buffers are chunks of audio data from any source.  A variety of nodes to work with buffers exist.
        pub fn Lav_createBuffer(
            serverHandle: root::LavHandle,
            destination: *mut root::LavHandle,
        ) -> root::LavError;
    }
    extern "C" {
        pub fn Lav_bufferGetServer(
            bufferHandle: root::LavHandle,
            destination: *mut root::LavHandle,
        ) -> root::LavError;
    }
    extern "C" {
        pub fn Lav_bufferLoadFromFile(
            bufferHandle: root::LavHandle,
            path: *const ::std::os::raw::c_char,
        ) -> root::LavError;
    }
    extern "C" {
        pub fn Lav_bufferLoadFromArray(
            bufferHandle: root::LavHandle,
            sr: ::std::os::raw::c_int,
            channels: ::std::os::raw::c_int,
            frames: ::std::os::raw::c_int,
            data: *mut f32,
        ) -> root::LavError;
    }
    extern "C" {
        pub fn Lav_bufferDecodeFromArray(
            bufferHandle: root::LavHandle,
            data: *mut ::std::os::raw::c_char,
            datalen: ::std::os::raw::c_int,
        ) -> root::LavError;
    }
    extern "C" {
        pub fn Lav_bufferNormalize(bufferHandle: root::LavHandle) -> root::LavError;
    }
    extern "C" {
        pub fn Lav_bufferGetDuration(
            bufferHandle: root::LavHandle,
            destination: *mut f32,
        ) -> root::LavError;
    }
    extern "C" {
        pub fn Lav_bufferGetLengthInSamples(
            bufferHandle: root::LavHandle,
            destination: *mut ::std::os::raw::c_int,
        ) -> root::LavError;
    }
    extern "C" {
        pub fn Lav_nodeGetServer(
            nodeHandle: root::LavHandle,
            destination: *mut root::LavHandle,
        ) -> root::LavError;
    }
    extern "C" {
        pub fn Lav_nodeConnect(
            nodeHandle: root::LavHandle,
            output: ::std::os::raw::c_int,
            destHandle: root::LavHandle,
            input: ::std::os::raw::c_int,
        ) -> root::LavError;
    }
    extern "C" {
        pub fn Lav_nodeConnectServer(
            nodeHandle: root::LavHandle,
            output: ::std::os::raw::c_int,
        ) -> root::LavError;
    }
    extern "C" {
        pub fn Lav_nodeConnectProperty(
            nodeHandle: root::LavHandle,
            output: ::std::os::raw::c_int,
            otherHandle: root::LavHandle,
            slot: ::std::os::raw::c_int,
        ) -> root::LavError;
    }
    extern "C" {
        pub fn Lav_nodeDisconnect(
            nodeHandle: root::LavHandle,
            output: ::std::os::raw::c_int,
            otherHandle: root::LavHandle,
            input: ::std::os::raw::c_int,
        ) -> root::LavError;
    }
    extern "C" {
        pub fn Lav_nodeIsolate(nodeHandle: root::LavHandle) -> root::LavError;
    }
    extern "C" {
        pub fn Lav_nodeGetInputConnectionCount(
            nodeHandle: root::LavHandle,
            destination: *mut ::std::os::raw::c_uint,
        ) -> root::LavError;
    }
    extern "C" {
        pub fn Lav_nodeGetOutputConnectionCount(
            nodeHandle: root::LavHandle,
            destination: *mut ::std::os::raw::c_uint,
        ) -> root::LavError;
    }
    extern "C" {
        pub fn Lav_nodeResetProperty(
            nodeHandle: root::LavHandle,
            propertyIndex: ::std::os::raw::c_int,
        ) -> root::LavError;
    }
    extern "C" {
        pub fn Lav_nodeSetIntProperty(
            nodeHandle: root::LavHandle,
            propertyIndex: ::std::os::raw::c_int,
            value: ::std::os::raw::c_int,
        ) -> root::LavError;
    }
    extern "C" {
        pub fn Lav_nodeSetFloatProperty(
            nodeHandle: root::LavHandle,
            propertyIndex: ::std::os::raw::c_int,
            value: f32,
        ) -> root::LavError;
    }
    extern "C" {
        pub fn Lav_nodeSetDoubleProperty(
            nodeHandle: root::LavHandle,
            propertyIndex: ::std::os::raw::c_int,
            value: f64,
        ) -> root::LavError;
    }
    extern "C" {
        pub fn Lav_nodeSetStringProperty(
            nodeHandle: root::LavHandle,
            propertyIndex: ::std::os::raw::c_int,
            value: *mut ::std::os::raw::c_char,
        ) -> root::LavError;
    }
    extern "C" {
        pub fn Lav_nodeSetFloat3Property(
            nodeHandle: root::LavHandle,
            propertyIndex: ::std::os::raw::c_int,
            v1: f32,
            v2: f32,
            v3: f32,
        ) -> root::LavError;
    }
    extern "C" {
        pub fn Lav_nodeSetFloat6Property(
            nodeHandle: root::LavHandle,
            propertyIndex: ::std::os::raw::c_int,
            v1: f32,
            v2: f32,
            v3: f32,
            v4: f32,
            v5: f32,
            v6: f32,
        ) -> root::LavError;
    }
    extern "C" {
        pub fn Lav_nodeGetIntProperty(
            nodeHandle: root::LavHandle,
            propertyIndex: ::std::os::raw::c_int,
            destination: *mut ::std::os::raw::c_int,
        ) -> root::LavError;
    }
    extern "C" {
        pub fn Lav_nodeGetFloatProperty(
            nodeHandle: root::LavHandle,
            propertyIndex: ::std::os::raw::c_int,
            destination: *mut f32,
        ) -> root::LavError;
    }
    extern "C" {
        pub fn Lav_nodeGetDoubleProperty(
            nodeHandle: root::LavHandle,
            propertyIndex: ::std::os::raw::c_int,
            destination: *mut f64,
        ) -> root::LavError;
    }
    extern "C" {
        pub fn Lav_nodeGetStringProperty(
            nodeHandle: root::LavHandle,
            propertyIndex: ::std::os::raw::c_int,
            destination: *mut *const ::std::os::raw::c_char,
        ) -> root::LavError;
    }
    extern "C" {
        pub fn Lav_nodeGetFloat3Property(
            nodeHandle: root::LavHandle,
            propertyIndex: ::std::os::raw::c_int,
            destination1: *mut f32,
            destination2: *mut f32,
            destination3: *mut f32,
        ) -> root::LavError;
    }
    extern "C" {
        pub fn Lav_nodeGetFloat6Property(
            nodeHandle: root::LavHandle,
            propertyIndex: ::std::os::raw::c_int,
            destinationV1: *mut f32,
            destinationV2: *mut f32,
            destinationV3: *mut f32,
            destinationV4: *mut f32,
            destinationV5: *mut f32,
            destinationV6: *mut f32,
        ) -> root::LavError;
    }
    extern "C" {
        pub fn Lav_nodeGetIntPropertyRange(
            nodeHandle: root::LavHandle,
            propertyIndex: ::std::os::raw::c_int,
            destinationMin: *mut ::std::os::raw::c_int,
            destinationMax: *mut ::std::os::raw::c_int,
        ) -> root::LavError;
    }
    extern "C" {
        pub fn Lav_nodeGetFloatPropertyRange(
            nodeHandle: root::LavHandle,
            propertyIndex: ::std::os::raw::c_int,
            destinationMin: *mut f32,
            destinationMax: *mut f32,
        ) -> root::LavError;
    }
    extern "C" {
        pub fn Lav_nodeGetDoublePropertyRange(
            nodeHandle: root::LavHandle,
            propertyIndex: ::std::os::raw::c_int,
            destinationMin: *mut f64,
            destinationMax: *mut f64,
        ) -> root::LavError;
    }
    extern "C" {
        pub fn Lav_nodeGetPropertyName(
            nodeHandle: root::LavHandle,
            propertyIndex: ::std::os::raw::c_int,
            destination: *mut *mut ::std::os::raw::c_char,
        ) -> root::LavError;
    }
    extern "C" {
        pub fn Lav_nodeGetPropertyType(
            nodeHandle: root::LavHandle,
            propertyIndex: ::std::os::raw::c_int,
            destination: *mut ::std::os::raw::c_int,
        ) -> root::LavError;
    }
    extern "C" {
        pub fn Lav_nodeGetPropertyHasDynamicRange(
            nodeHandle: root::LavHandle,
            propertyIndex: ::std::os::raw::c_int,
            destination: *mut ::std::os::raw::c_int,
        ) -> root::LavError;
    }
    extern "C" {
        pub fn Lav_nodeReplaceFloatArrayProperty(
            nodeHandle: root::LavHandle,
            propertyIndex: ::std::os::raw::c_int,
            length: ::std::os::raw::c_uint,
            values: *mut f32,
        ) -> root::LavError;
    }
    extern "C" {
        pub fn Lav_nodeReadFloatArrayProperty(
            nodeHandle: root::LavHandle,
            propertyIndex: ::std::os::raw::c_int,
            index: ::std::os::raw::c_uint,
            destination: *mut f32,
        ) -> root::LavError;
    }
    extern "C" {
        pub fn Lav_nodeWriteFloatArrayProperty(
            nodeHandle: root::LavHandle,
            propertyIndex: ::std::os::raw::c_int,
            start: ::std::os::raw::c_uint,
            stop: ::std::os::raw::c_uint,
            values: *mut f32,
        ) -> root::LavError;
    }
    extern "C" {
        pub fn Lav_nodeGetFloatArrayPropertyLength(
            nodeHandle: root::LavHandle,
            propertyIndex: ::std::os::raw::c_int,
            destination: *mut ::std::os::raw::c_uint,
        ) -> root::LavError;
    }
    extern "C" {
        pub fn Lav_nodeReplaceIntArrayProperty(
            nodeHandle: root::LavHandle,
            propertyIndex: ::std::os::raw::c_int,
            length: ::std::os::raw::c_uint,
            values: *mut ::std::os::raw::c_int,
        ) -> root::LavError;
    }
    extern "C" {
        pub fn Lav_nodeReadIntArrayProperty(
            nodeHandle: root::LavHandle,
            propertyIndex: ::std::os::raw::c_int,
            index: ::std::os::raw::c_uint,
            destination: *mut ::std::os::raw::c_int,
        ) -> root::LavError;
    }
    extern "C" {
        pub fn Lav_nodeWriteIntArrayProperty(
            nodeHandle: root::LavHandle,
            propertyIndex: ::std::os::raw::c_int,
            start: ::std::os::raw::c_uint,
            stop: ::std::os::raw::c_uint,
            values: *mut ::std::os::raw::c_int,
        ) -> root::LavError;
    }
    extern "C" {
        pub fn Lav_nodeGetIntArrayPropertyLength(
            nodeHandle: root::LavHandle,
            propertyIndex: ::std::os::raw::c_int,
            destination: *mut ::std::os::raw::c_int,
        ) -> root::LavError;
    }
    extern "C" {
        pub fn Lav_nodeGetArrayPropertyLengthRange(
            nodeHandle: root::LavHandle,
            propertyIndex: ::std::os::raw::c_int,
            destinationMin: *mut ::std::os::raw::c_uint,
            destinationMax: *mut ::std::os::raw::c_uint,
        ) -> root::LavError;
    }
    extern "C" {
        pub fn Lav_nodeSetBufferProperty(
            nodeHandle: root::LavHandle,
            propertyIndex: ::std::os::raw::c_int,
            value: root::LavHandle,
        ) -> root::LavError;
    }
    extern "C" {
        pub fn Lav_nodeGetBufferProperty(
            nodeHandle: root::LavHandle,
            propertyIndex: ::std::os::raw::c_int,
            destination: *mut root::LavHandle,
        ) -> root::LavError;
    }
    extern "C" {
        pub fn Lav_automationCancelAutomators(
            nodeHandle: root::LavHandle,
            propertyIndex: ::std::os::raw::c_int,
            time: f64,
        ) -> root::LavError;
    }
    extern "C" {
        pub fn Lav_automationLinearRampToValue(
            nodeHandle: root::LavHandle,
            slot: ::std::os::raw::c_int,
            time: f64,
            value: f64,
        ) -> root::LavError;
    }
    extern "C" {
        pub fn Lav_automationSet(
            nodeHandle: root::LavHandle,
            slot: ::std::os::raw::c_int,
            time: f64,
            value: f64,
        ) -> root::LavError;
    }
    extern "C" {
        pub fn Lav_automationEnvelope(
            nodeHandle: root::LavHandle,
            slot: ::std::os::raw::c_int,
            time: f64,
            duration: f64,
            valuesLength: ::std::os::raw::c_int,
            values: *mut f64,
        ) -> root::LavError;
    }
    extern "C" {
        pub fn Lav_nodeReset(nodeHandle: root::LavHandle) -> root::LavError;
    }
    extern "C" {
        pub fn Lav_createSineNode(
            serverHandle: root::LavHandle,
            destination: *mut root::LavHandle,
        ) -> root::LavError;
    }
    extern "C" {
        pub fn Lav_createAdditiveSquareNode(
            serverHandle: root::LavHandle,
            destination: *mut root::LavHandle,
        ) -> root::LavError;
    }
    extern "C" {
        pub fn Lav_createAdditiveTriangleNode(
            serverHandle: root::LavHandle,
            destination: *mut root::LavHandle,
        ) -> root::LavError;
    }
    extern "C" {
        pub fn Lav_createAdditiveSawNode(
            serverHandle: root::LavHandle,
            destination: *mut root::LavHandle,
        ) -> root::LavError;
    }
    extern "C" {
        pub fn Lav_createNoiseNode(
            serverHandle: root::LavHandle,
            destination: *mut root::LavHandle,
        ) -> root::LavError;
    }
    extern "C" {
        pub fn Lav_createHrtfNode(
            serverHandle: root::LavHandle,
            hrtfPath: *const ::std::os::raw::c_char,
            destination: *mut root::LavHandle,
        ) -> root::LavError;
    }
    extern "C" {
        pub fn Lav_createHardLimiterNode(
            serverHandle: root::LavHandle,
            channels: ::std::os::raw::c_int,
            destination: *mut root::LavHandle,
        ) -> root::LavError;
    }
    extern "C" {
        pub fn Lav_createCrossfadingDelayNode(
            serverHandle: root::LavHandle,
            maxDelay: f32,
            channels: ::std::os::raw::c_int,
            destination: *mut root::LavHandle,
        ) -> root::LavError;
    }
    extern "C" {
        pub fn Lav_createDoppleringDelayNode(
            serverHandle: root::LavHandle,
            maxDelay: f32,
            channels: ::std::os::raw::c_int,
            destination: *mut root::LavHandle,
        ) -> root::LavError;
    }
    extern "C" {
        pub fn Lav_createAmplitudePannerNode(
            serverHandle: root::LavHandle,
            destination: *mut root::LavHandle,
        ) -> root::LavError;
    }
    extern "C" {
        pub fn Lav_amplitudePannerNodeConfigureStandardMap(
            nodeHandle: root::LavHandle,
            channels: ::std::os::raw::c_uint,
        ) -> root::LavError;
    }
    extern "C" {
        pub fn Lav_createMultipannerNode(
            serverHandle: root::LavHandle,
            hrtfPath: *mut ::std::os::raw::c_char,
            destination: *mut root::LavHandle,
        ) -> root::LavError;
    }
    extern "C" {
        pub fn Lav_createPushNode(
            serverHandle: root::LavHandle,
            sr: ::std::os::raw::c_uint,
            channels: ::std::os::raw::c_uint,
            destination: *mut root::LavHandle,
        ) -> root::LavError;
    }
    extern "C" {
        pub fn Lav_pushNodeFeed(
            nodeHandle: root::LavHandle,
            length: ::std::os::raw::c_uint,
            frames: *mut f32,
        ) -> root::LavError;
    }
    extern "C" {
        pub fn Lav_pushNodeSetLowCallback(
            nodeHandle: root::LavHandle,
            callback: root::LavParameterlessCallback,
            userdata: *mut ::std::os::raw::c_void,
        ) -> root::LavError;
    }
    extern "C" {
        pub fn Lav_pushNodeSetUnderrunCallback(
            nodeHandle: root::LavHandle,
            callback: root::LavParameterlessCallback,
            userdata: *mut ::std::os::raw::c_void,
        ) -> root::LavError;
    }
    extern "C" {
        pub fn Lav_createBiquadNode(
            serverHandle: root::LavHandle,
            channels: ::std::os::raw::c_uint,
            destination: *mut root::LavHandle,
        ) -> root::LavError;
    }
    pub type LavPullNodeAudioCallback = ::std::option::Option<
        unsafe extern "C" fn(
            nodeHandle: root::LavHandle,
            frames: ::std::os::raw::c_int,
            channels: ::std::os::raw::c_int,
            buffer: *mut f32,
            userdata: *mut ::std::os::raw::c_void,
        ),
    >;
    extern "C" {
        pub fn Lav_createPullNode(
            serverHandle: root::LavHandle,
            sr: ::std::os::raw::c_uint,
            channels: ::std::os::raw::c_uint,
            destination: *mut root::LavHandle,
        ) -> root::LavError;
    }
    extern "C" {
        pub fn Lav_pullNodeSetAudioCallback(
            nodeHandle: root::LavHandle,
            callback: root::LavPullNodeAudioCallback,
            userdata: *mut ::std::os::raw::c_void,
        ) -> root::LavError;
    }
    pub type LavGraphListenerNodeListeningCallback = ::std::option::Option<
        unsafe extern "C" fn(
            nodeHandle: root::LavHandle,
            frames: ::std::os::raw::c_uint,
            channels: ::std::os::raw::c_uint,
            buffer: *mut f32,
            userdata: *mut ::std::os::raw::c_void,
        ),
    >;
    extern "C" {
        pub fn Lav_createGraphListenerNode(
            serverHandle: root::LavHandle,
            channels: ::std::os::raw::c_uint,
            destination: *mut root::LavHandle,
        ) -> root::LavError;
    }
    extern "C" {
        pub fn Lav_graphListenerNodeSetListeningCallback(
            nodeHandle: root::LavHandle,
            callback: root::LavGraphListenerNodeListeningCallback,
            userdata: *mut ::std::os::raw::c_void,
        ) -> root::LavError;
    }
    extern "C" {
        pub fn Lav_createRingmodNode(
            serverHandle: root::LavHandle,
            destination: *mut root::LavHandle,
        ) -> root::LavError;
    }
    extern "C" {
        pub fn Lav_createFeedbackDelayNetworkNode(
            serverHandle: root::LavHandle,
            maxDelay: f32,
            channels: ::std::os::raw::c_int,
            destination: *mut root::LavHandle,
        ) -> root::LavError;
    }
    extern "C" {
        pub fn Lav_createIirNode(
            serverHandle: root::LavHandle,
            channels: ::std::os::raw::c_int,
            destination: *mut root::LavHandle,
        ) -> root::LavError;
    }
    extern "C" {
        pub fn Lav_iirNodeSetCoefficients(
            nodeHandle: root::LavHandle,
            numeratorLength: ::std::os::raw::c_int,
            numerator: *mut f64,
            denominatorLength: ::std::os::raw::c_int,
            denominator: *mut f64,
            shouldClearHistory: ::std::os::raw::c_int,
        ) -> root::LavError;
    }
    extern "C" {
        pub fn Lav_createGainNode(
            serverHandle: root::LavHandle,
            channels: ::std::os::raw::c_int,
            destination: *mut root::LavHandle,
        ) -> root::LavError;
    }
    extern "C" {
        pub fn Lav_createChannelSplitterNode(
            serverHandle: root::LavHandle,
            channels: ::std::os::raw::c_int,
            destination: *mut root::LavHandle,
        ) -> root::LavError;
    }
    extern "C" {
        pub fn Lav_createChannelMergerNode(
            serverHandle: root::LavHandle,
            channels: ::std::os::raw::c_int,
            destination: *mut root::LavHandle,
        ) -> root::LavError;
    }
    extern "C" {
        pub fn Lav_createBufferNode(
            serverHandle: root::LavHandle,
            destination: *mut root::LavHandle,
        ) -> root::LavError;
    }
    extern "C" {
        pub fn Lav_bufferNodeSetEndCallback(
            nodeHandle: root::LavHandle,
            callback: root::LavParameterlessCallback,
            userdata: *mut ::std::os::raw::c_void,
        ) -> root::LavError;
    }
    extern "C" {
        pub fn Lav_createBufferTimelineNode(
            serverHandle: root::LavHandle,
            channels: ::std::os::raw::c_int,
            destination: *mut root::LavHandle,
        ) -> root::LavError;
    }
    extern "C" {
        pub fn Lav_bufferTimelineNodeScheduleBuffer(
            nodeHandle: root::LavHandle,
            bufferHandle: root::LavHandle,
            time: f64,
            pitchBend: f32,
        ) -> root::LavError;
    }
    extern "C" {
        pub fn Lav_createRecorderNode(
            serverHandle: root::LavHandle,
            channels: ::std::os::raw::c_int,
            destination: *mut root::LavHandle,
        ) -> root::LavError;
    }
    extern "C" {
        pub fn Lav_recorderNodeStartRecording(
            nodeHandle: root::LavHandle,
            path: *const ::std::os::raw::c_char,
        ) -> root::LavError;
    }
    extern "C" {
        pub fn Lav_recorderNodeStopRecording(nodeHandle: root::LavHandle) -> root::LavError;
    }
    extern "C" {
        pub fn Lav_createConvolverNode(
            serverHandle: root::LavHandle,
            channels: ::std::os::raw::c_int,
            destination: *mut root::LavHandle,
        ) -> root::LavError;
    }
    extern "C" {
        pub fn Lav_createFftConvolverNode(
            serverHandle: root::LavHandle,
            channels: ::std::os::raw::c_int,
            destination: *mut root::LavHandle,
        ) -> root::LavError;
    }
    extern "C" {
        pub fn Lav_fftConvolverNodeSetResponse(
            nodeHandle: root::LavHandle,
            channel: ::std::os::raw::c_int,
            length: ::std::os::raw::c_int,
            response: *mut f32,
        ) -> root::LavError;
    }
    extern "C" {
        pub fn Lav_fftConvolverNodeSetResponseFromFile(
            nodeHandle: root::LavHandle,
            path: *const ::std::os::raw::c_char,
            fileChannel: ::std::os::raw::c_int,
            convolverChannel: ::std::os::raw::c_int,
        ) -> root::LavError;
    }
    extern "C" {
        pub fn Lav_createThreeBandEqNode(
            serverHandle: root::LavHandle,
            channels: ::std::os::raw::c_int,
            destination: *mut root::LavHandle,
        ) -> root::LavError;
    }
    extern "C" {
        pub fn Lav_createFilteredDelayNode(
            serverHandle: root::LavHandle,
            maxDelay: f32,
            channels: ::std::os::raw::c_uint,
            destination: *mut root::LavHandle,
        ) -> root::LavError;
    }
    extern "C" {
        pub fn Lav_createCrossfaderNode(
            serverHandle: root::LavHandle,
            channels: ::std::os::raw::c_int,
            inputs: ::std::os::raw::c_int,
            destination: *mut root::LavHandle,
        ) -> root::LavError;
    }
    extern "C" {
        pub fn Lav_crossfaderNodeCrossfade(
            nodeHandle: root::LavHandle,
            duration: f32,
            input: ::std::os::raw::c_int,
        ) -> root::LavError;
    }
    extern "C" {
        pub fn Lav_crossfaderNodeSetFinishedCallback(
            nodeHandle: root::LavHandle,
            callback: root::LavParameterlessCallback,
            userdata: *mut ::std::os::raw::c_void,
        ) -> root::LavError;
    }
    extern "C" {
        pub fn Lav_createOnePoleFilterNode(
            serverHandle: root::LavHandle,
            channels: ::std::os::raw::c_int,
            destination: *mut root::LavHandle,
        ) -> root::LavError;
    }
    extern "C" {
        pub fn Lav_createFirstOrderFilterNode(
            serverHandle: root::LavHandle,
            channels: ::std::os::raw::c_int,
            destination: *mut root::LavHandle,
        ) -> root::LavError;
    }
    extern "C" {
        pub fn Lav_firstOrderFilterNodeConfigureLowpass(
            nodeHandle: root::LavHandle,
            frequency: f32,
        ) -> root::LavError;
    }
    extern "C" {
        pub fn Lav_firstOrderFilterNodeConfigureHighpass(
            nodeHandle: root::LavHandle,
            frequency: f32,
        ) -> root::LavError;
    }
    extern "C" {
        pub fn Lav_firstOrderFilterNodeConfigureAllpass(
            nodeHandle: root::LavHandle,
            frequency: f32,
        ) -> root::LavError;
    }
    extern "C" {
        pub fn Lav_createAllpassNode(
            serverHandle: root::LavHandle,
            channels: ::std::os::raw::c_int,
            maxDelay: ::std::os::raw::c_int,
            destination: *mut root::LavHandle,
        ) -> root::LavError;
    }
    extern "C" {
        pub fn Lav_createFdnReverbNode(
            serverHandle: root::LavHandle,
            destination: *mut root::LavHandle,
        ) -> root::LavError;
    }
    extern "C" {
        pub fn Lav_createBlitNode(
            serverHandle: root::LavHandle,
            destination: *mut root::LavHandle,
        ) -> root::LavError;
    }
    extern "C" {
        pub fn Lav_createDcBlockerNode(
            serverHandle: root::LavHandle,
            channels: ::std::os::raw::c_int,
            destination: *mut root::LavHandle,
        ) -> root::LavError;
    }
    extern "C" {
        pub fn Lav_createLeakyIntegratorNode(
            serverHandle: root::LavHandle,
            channels: ::std::os::raw::c_int,
            destination: *mut root::LavHandle,
        ) -> root::LavError;
    }
    extern "C" {
        pub fn Lav_createFileStreamerNode(
            serverHandle: root::LavHandle,
            path: *const ::std::os::raw::c_char,
            destination: *mut root::LavHandle,
        ) -> root::LavError;
    }
    extern "C" {
        pub fn Lav_fileStreamerNodeSetEndCallback(
            nodeHandle: root::LavHandle,
            callback: root::LavParameterlessCallback,
            userdata: *mut ::std::os::raw::c_void,
        ) -> root::LavError;
    }
    pub const lav_STANDARD_PROPERTIES_Lav_NODE_STATE: root::lav_STANDARD_PROPERTIES = -100;
    pub const lav_STANDARD_PROPERTIES_Lav_NODE_MUL: root::lav_STANDARD_PROPERTIES = -101;
    pub const lav_STANDARD_PROPERTIES_Lav_NODE_ADD: root::lav_STANDARD_PROPERTIES = -102;
    pub const lav_STANDARD_PROPERTIES_Lav_NODE_CHANNEL_INTERPRETATION:
        root::lav_STANDARD_PROPERTIES = -104;
    /// This file contains the property enums for Libaudioverse.
    ///
    /// It is worth keeping separate because it will grow rapidly and contain documentation comments and etc.
    ///
    /// The standard for naming is:
    /// Lav_NODETYPE_PROPNAME
    ///
    /// Furthermore, all libaudioverse properties are negative.
    ///
    /// Values below -100 are reserved for standard events and properties on all objects.
    pub type lav_STANDARD_PROPERTIES = i32;
    pub const Lav_CHANNEL_INTERPRETATIONS_Lav_CHANNEL_INTERPRETATION_DISCRETE:
        root::Lav_CHANNEL_INTERPRETATIONS = 0;
    pub const Lav_CHANNEL_INTERPRETATIONS_Lav_CHANNEL_INTERPRETATION_SPEAKERS:
        root::Lav_CHANNEL_INTERPRETATIONS = 1;
    pub type Lav_CHANNEL_INTERPRETATIONS = i32;
    pub const Lav_OSCILLATOR_PROPERTIES_Lav_OSCILLATOR_FREQUENCY: root::Lav_OSCILLATOR_PROPERTIES =
        -200;
    pub const Lav_OSCILLATOR_PROPERTIES_Lav_OSCILLATOR_PHASE: root::Lav_OSCILLATOR_PROPERTIES =
        -201;
    pub const Lav_OSCILLATOR_PROPERTIES_Lav_OSCILLATOR_FREQUENCY_MULTIPLIER:
        root::Lav_OSCILLATOR_PROPERTIES = -202;
    pub type Lav_OSCILLATOR_PROPERTIES = i32;
    pub const lav_SQUARE_PROPERTIES_Lav_SQUARE_HARMONICS: root::lav_SQUARE_PROPERTIES = -1;
    pub const lav_SQUARE_PROPERTIES_Lav_SQUARE_DUTY_CYCLE: root::lav_SQUARE_PROPERTIES = -2;
    pub type lav_SQUARE_PROPERTIES = i32;
    pub const lav_TRIANGLE_PROPERTIES_Lav_TRIANGLE_HARMONICS: root::lav_TRIANGLE_PROPERTIES = -3;
    pub type lav_TRIANGLE_PROPERTIES = i32;
    pub const lav_SAW_PROPERTIES_Lav_SAW_HARMONICS: root::lav_SAW_PROPERTIES = -3;
    pub type lav_SAW_PROPERTIES = i32;
    pub const Lav_NOISE_PROPERTIES_Lav_NOISE_NOISE_TYPE: root::Lav_NOISE_PROPERTIES = -1;
    pub const Lav_NOISE_PROPERTIES_Lav_NOISE_SHOULD_NORMALIZE: root::Lav_NOISE_PROPERTIES = -2;
    pub type Lav_NOISE_PROPERTIES = i32;
    pub const Lav_NOISE_TYPES_Lav_NOISE_TYPE_WHITE: root::Lav_NOISE_TYPES = 0;
    pub const Lav_NOISE_TYPES_Lav_NOISE_TYPE_PINK: root::Lav_NOISE_TYPES = 1;
    pub const Lav_NOISE_TYPES_Lav_NOISE_TYPE_BROWN: root::Lav_NOISE_TYPES = 2;
    pub type Lav_NOISE_TYPES = i32;
    pub const Lav_PANNER_PROPERTIES_Lav_PANNER_AZIMUTH: root::Lav_PANNER_PROPERTIES = -1;
    pub const Lav_PANNER_PROPERTIES_Lav_PANNER_ELEVATION: root::Lav_PANNER_PROPERTIES = -2;
    pub const Lav_PANNER_PROPERTIES_Lav_PANNER_CHANNEL_MAP: root::Lav_PANNER_PROPERTIES = -3;
    pub const Lav_PANNER_PROPERTIES_Lav_PANNER_SHOULD_CROSSFADE: root::Lav_PANNER_PROPERTIES = -4;
    pub const Lav_PANNER_PROPERTIES_Lav_PANNER_STRATEGY: root::Lav_PANNER_PROPERTIES = -5;
    pub type Lav_PANNER_PROPERTIES = i32;
    pub const Lav_PANNER_BANK_PROPERTIES_Lav_PANNER_BANK_SPREAD: root::Lav_PANNER_BANK_PROPERTIES =
        -20;
    pub const Lav_PANNER_BANK_PROPERTIES_Lav_PANNER_BANK_COUNT: root::Lav_PANNER_BANK_PROPERTIES =
        -21;
    pub const Lav_PANNER_BANK_PROPERTIES_Lav_PANNER_BANK_IS_CENTERED:
        root::Lav_PANNER_BANK_PROPERTIES = -22;
    pub type Lav_PANNER_BANK_PROPERTIES = i32;
    pub const Lav_PANNING_STRATEGIES_Lav_PANNING_STRATEGY_HRTF: root::Lav_PANNING_STRATEGIES = 0;
    pub const Lav_PANNING_STRATEGIES_Lav_PANNING_STRATEGY_STEREO: root::Lav_PANNING_STRATEGIES = 1;
    pub const Lav_PANNING_STRATEGIES_Lav_PANNING_STRATEGY_SURROUND40: root::Lav_PANNING_STRATEGIES =
        2;
    pub const Lav_PANNING_STRATEGIES_Lav_PANNING_STRATEGY_SURROUND51: root::Lav_PANNING_STRATEGIES =
        3;
    pub const Lav_PANNING_STRATEGIES_Lav_PANNING_STRATEGY_SURROUND71: root::Lav_PANNING_STRATEGIES =
        4;
    pub type Lav_PANNING_STRATEGIES = i32;
    pub const Lav_MIXER_PROPERTIES_Lav_MIXER_MAX_PARENTS: root::Lav_MIXER_PROPERTIES = -1;
    pub const Lav_MIXER_PROPERTIES_Lav_MIXER_INPUTS_PER_PARENT: root::Lav_MIXER_PROPERTIES = -2;
    pub type Lav_MIXER_PROPERTIES = i32;
    pub const Lav_DELAY_PROPERTIES_Lav_DELAY_DELAY: root::Lav_DELAY_PROPERTIES = -1;
    pub const Lav_DELAY_PROPERTIES_Lav_DELAY_DELAY_MAX: root::Lav_DELAY_PROPERTIES = -2;
    pub const Lav_DELAY_PROPERTIES_Lav_DELAY_FEEDBACK: root::Lav_DELAY_PROPERTIES = -3;
    pub const Lav_DELAY_PROPERTIES_Lav_DELAY_INTERPOLATION_TIME: root::Lav_DELAY_PROPERTIES = -4;
    pub type Lav_DELAY_PROPERTIES = i32;
    pub const Lav_PUSH_NODE_PROPERTIES_Lav_PUSH_THRESHOLD: root::Lav_PUSH_NODE_PROPERTIES = -1;
    pub type Lav_PUSH_NODE_PROPERTIES = i32;
    pub const Lav_BIQUAD_PROPERTIES_Lav_BIQUAD_FILTER_TYPE: root::Lav_BIQUAD_PROPERTIES = -1;
    pub const Lav_BIQUAD_PROPERTIES_Lav_BIQUAD_Q: root::Lav_BIQUAD_PROPERTIES = -2;
    pub const Lav_BIQUAD_PROPERTIES_Lav_BIQUAD_FREQUENCY: root::Lav_BIQUAD_PROPERTIES = -3;
    pub const Lav_BIQUAD_PROPERTIES_Lav_BIQUAD_DBGAIN: root::Lav_BIQUAD_PROPERTIES = -4;
    pub type Lav_BIQUAD_PROPERTIES = i32;
    pub const Lav_BIQUAD_TYPES_Lav_BIQUAD_TYPE_LOWPASS: root::Lav_BIQUAD_TYPES = 0;
    pub const Lav_BIQUAD_TYPES_Lav_BIQUAD_TYPE_HIGHPASS: root::Lav_BIQUAD_TYPES = 1;
    pub const Lav_BIQUAD_TYPES_Lav_BIQUAD_TYPE_BANDPASS: root::Lav_BIQUAD_TYPES = 2;
    pub const Lav_BIQUAD_TYPES_Lav_BIQUAD_TYPE_NOTCH: root::Lav_BIQUAD_TYPES = 3;
    pub const Lav_BIQUAD_TYPES_Lav_BIQUAD_TYPE_ALLPASS: root::Lav_BIQUAD_TYPES = 4;
    pub const Lav_BIQUAD_TYPES_Lav_BIQUAD_TYPE_PEAKING: root::Lav_BIQUAD_TYPES = 5;
    pub const Lav_BIQUAD_TYPES_Lav_BIQUAD_TYPE_LOWSHELF: root::Lav_BIQUAD_TYPES = 6;
    pub const Lav_BIQUAD_TYPES_Lav_BIQUAD_TYPE_HIGHSHELF: root::Lav_BIQUAD_TYPES = 7;
    pub const Lav_BIQUAD_TYPES_Lav_BIQUAD_TYPE_IDENTITY: root::Lav_BIQUAD_TYPES = 8;
    pub type Lav_BIQUAD_TYPES = i32;
    pub const Lav_FEEDBACK_DELAY_NETWORK_PROPERTIES_Lav_FDN_MAX_DELAY:
        root::Lav_FEEDBACK_DELAY_NETWORK_PROPERTIES = -1;
    pub const Lav_FEEDBACK_DELAY_NETWORK_PROPERTIES_Lav_FDN_OUTPUT_GAINS:
        root::Lav_FEEDBACK_DELAY_NETWORK_PROPERTIES = -2;
    pub const Lav_FEEDBACK_DELAY_NETWORK_PROPERTIES_Lav_FDN_DELAYS:
        root::Lav_FEEDBACK_DELAY_NETWORK_PROPERTIES = -3;
    pub const Lav_FEEDBACK_DELAY_NETWORK_PROPERTIES_Lav_FDN_MATRIX:
        root::Lav_FEEDBACK_DELAY_NETWORK_PROPERTIES = -4;
    pub const Lav_FEEDBACK_DELAY_NETWORK_PROPERTIES_Lav_FDN_FILTER_TYPES:
        root::Lav_FEEDBACK_DELAY_NETWORK_PROPERTIES = -5;
    pub const Lav_FEEDBACK_DELAY_NETWORK_PROPERTIES_Lav_FDN_FILTER_FREQUENCIES:
        root::Lav_FEEDBACK_DELAY_NETWORK_PROPERTIES = -6;
    pub type Lav_FEEDBACK_DELAY_NETWORK_PROPERTIES = i32;
    pub const Lav_FDN_FILTER_TYPES_Lav_FDN_FILTER_TYPE_DISABLED: root::Lav_FDN_FILTER_TYPES = 0;
    pub const Lav_FDN_FILTER_TYPES_Lav_FDN_FILTER_TYPE_LOWPASS: root::Lav_FDN_FILTER_TYPES = 1;
    pub const Lav_FDN_FILTER_TYPES_Lav_FDN_FILTER_TYPE_HIGHPASS: root::Lav_FDN_FILTER_TYPES = 2;
    pub type Lav_FDN_FILTER_TYPES = i32;
    pub const Lav_BUFFER_PROPERTIES_Lav_BUFFER_BUFFER: root::Lav_BUFFER_PROPERTIES = -1;
    pub const Lav_BUFFER_PROPERTIES_Lav_BUFFER_POSITION: root::Lav_BUFFER_PROPERTIES = -2;
    pub const Lav_BUFFER_PROPERTIES_Lav_BUFFER_RATE: root::Lav_BUFFER_PROPERTIES = -3;
    pub const Lav_BUFFER_PROPERTIES_Lav_BUFFER_LOOPING: root::Lav_BUFFER_PROPERTIES = -4;
    pub const Lav_BUFFER_PROPERTIES_Lav_BUFFER_ENDED_COUNT: root::Lav_BUFFER_PROPERTIES = -5;
    pub type Lav_BUFFER_PROPERTIES = i32;
    pub const Lav_CONVOLVER_PROPERTIES_Lav_CONVOLVER_IMPULSE_RESPONSE:
        root::Lav_CONVOLVER_PROPERTIES = -1;
    pub type Lav_CONVOLVER_PROPERTIES = i32;
    pub const Lav_THREE_BAND_EQ_PROPERTIES_Lav_THREE_BAND_EQ_HIGHBAND_DBGAIN:
        root::Lav_THREE_BAND_EQ_PROPERTIES = -1;
    pub const Lav_THREE_BAND_EQ_PROPERTIES_Lav_THREE_BAND_EQ_HIGHBAND_FREQUENCY:
        root::Lav_THREE_BAND_EQ_PROPERTIES = -2;
    pub const Lav_THREE_BAND_EQ_PROPERTIES_Lav_THREE_BAND_EQ_MIDBAND_DBGAIN:
        root::Lav_THREE_BAND_EQ_PROPERTIES = -3;
    pub const Lav_THREE_BAND_EQ_PROPERTIES_Lav_THREE_BAND_EQ_LOWBAND_DBGAIN:
        root::Lav_THREE_BAND_EQ_PROPERTIES = -4;
    pub const Lav_THREE_BAND_EQ_PROPERTIES_Lav_THREE_BAND_EQ_LOWBAND_FREQUENCY:
        root::Lav_THREE_BAND_EQ_PROPERTIES = -5;
    pub type Lav_THREE_BAND_EQ_PROPERTIES = i32;
    pub const Lav_FILTERED_DELAY_PROPERTIES_Lav_FILTERED_DELAY_DELAY:
        root::Lav_FILTERED_DELAY_PROPERTIES = -1;
    pub const Lav_FILTERED_DELAY_PROPERTIES_Lav_FILTERED_DELAY_FEEDBACK:
        root::Lav_FILTERED_DELAY_PROPERTIES = -2;
    pub const Lav_FILTERED_DELAY_PROPERTIES_Lav_FILTERED_DELAY_INTERPOLATION_TIME:
        root::Lav_FILTERED_DELAY_PROPERTIES = -3;
    pub const Lav_FILTERED_DELAY_PROPERTIES_Lav_FILTERED_DELAY_DELAY_MAX:
        root::Lav_FILTERED_DELAY_PROPERTIES = -4;
    pub const Lav_FILTERED_DELAY_PROPERTIES_Lav_FILTERED_DELAY_FILTER_TYPE:
        root::Lav_FILTERED_DELAY_PROPERTIES = -5;
    pub const Lav_FILTERED_DELAY_PROPERTIES_Lav_FILTERED_DELAY_Q:
        root::Lav_FILTERED_DELAY_PROPERTIES = -6;
    pub const Lav_FILTERED_DELAY_PROPERTIES_Lav_FILTERED_DELAY_FREQUENCY:
        root::Lav_FILTERED_DELAY_PROPERTIES = -7;
    pub const Lav_FILTERED_DELAY_PROPERTIES_Lav_FILTERED_DELAY_DBGAIN:
        root::Lav_FILTERED_DELAY_PROPERTIES = -8;
    pub type Lav_FILTERED_DELAY_PROPERTIES = i32;
    pub const Lav_CROSSFADER_PROPERTIES_Lav_CROSSFADER_CURRENT_INPUT:
        root::Lav_CROSSFADER_PROPERTIES = -1;
    pub const Lav_CROSSFADER_PROPERTIES_Lav_CROSSFADER_TARGET_INPUT:
        root::Lav_CROSSFADER_PROPERTIES = -2;
    pub const Lav_CROSSFADER_PROPERTIES_Lav_CROSSFADER_IS_CROSSFADING:
        root::Lav_CROSSFADER_PROPERTIES = -3;
    pub type Lav_CROSSFADER_PROPERTIES = i32;
    pub const Lav_ONE_POLE_FILTER_PROPERTIES_Lav_ONE_POLE_FILTER_FREQUENCY:
        root::Lav_ONE_POLE_FILTER_PROPERTIES = -1;
    pub const Lav_ONE_POLE_FILTER_PROPERTIES_Lav_ONE_POLE_FILTER_IS_HIGHPASS:
        root::Lav_ONE_POLE_FILTER_PROPERTIES = -2;
    pub type Lav_ONE_POLE_FILTER_PROPERTIES = i32;
    pub const Lav_FIRST_ORDER_FILTER_PROPERTIES_Lav_FIRST_ORDER_FILTER_POLE:
        root::Lav_FIRST_ORDER_FILTER_PROPERTIES = -1;
    pub const Lav_FIRST_ORDER_FILTER_PROPERTIES_Lav_FIRST_ORDER_FILTER_ZERO:
        root::Lav_FIRST_ORDER_FILTER_PROPERTIES = -2;
    pub type Lav_FIRST_ORDER_FILTER_PROPERTIES = i32;
    pub const Lav_ALLPASS_OPROPERTIES_Lav_ALLPASS_DELAY_SAMPLES: root::Lav_ALLPASS_OPROPERTIES = -1;
    pub const Lav_ALLPASS_OPROPERTIES_Lav_ALLPASS_DELAY_SAMPLES_MAX: root::Lav_ALLPASS_OPROPERTIES =
        -2;
    pub const Lav_ALLPASS_OPROPERTIES_Lav_ALLPASS_INTERPOLATION_TIME:
        root::Lav_ALLPASS_OPROPERTIES = -3;
    pub const Lav_ALLPASS_OPROPERTIES_Lav_ALLPASS_COEFFICIENT: root::Lav_ALLPASS_OPROPERTIES = -4;
    pub type Lav_ALLPASS_OPROPERTIES = i32;
    pub const Lav_FDN_REVERB_PROPERTIES_Lav_FDN_REVERB_T60: root::Lav_FDN_REVERB_PROPERTIES = -1;
    pub const Lav_FDN_REVERB_PROPERTIES_Lav_FDN_REVERB_CUTOFF_FREQUENCY:
        root::Lav_FDN_REVERB_PROPERTIES = -2;
    pub const Lav_FDN_REVERB_PROPERTIES_Lav_FDN_REVERB_DENSITY: root::Lav_FDN_REVERB_PROPERTIES =
        -3;
    pub const Lav_FDN_REVERB_PROPERTIES_Lav_FDN_REVERB_DELAY_MODULATION_DEPTH:
        root::Lav_FDN_REVERB_PROPERTIES = -4;
    pub const Lav_FDN_REVERB_PROPERTIES_Lav_FDN_REVERB_DELAY_MODULATION_FREQUENCY:
        root::Lav_FDN_REVERB_PROPERTIES = -5;
    pub type Lav_FDN_REVERB_PROPERTIES = i32;
    pub const Lav_BLIT_PROPERTIES_Lav_BLIT_HARMONICS: root::Lav_BLIT_PROPERTIES = -1;
    pub const Lav_BLIT_PROPERTIES_Lav_BLIT_SHOULD_NORMALIZE: root::Lav_BLIT_PROPERTIES = -4;
    pub type Lav_BLIT_PROPERTIES = i32;
    pub const Lav_LEAKY_INTEGRATOR_PROPERTIES_Lav_LEAKY_INTEGRATOR_LEAKYNESS:
        root::Lav_LEAKY_INTEGRATOR_PROPERTIES = -1;
    pub type Lav_LEAKY_INTEGRATOR_PROPERTIES = i32;
    pub const Lav_FILE_STREAMER_PROPERTIES_Lav_FILE_STREAMER_POSITION:
        root::Lav_FILE_STREAMER_PROPERTIES = -1;
    pub const Lav_FILE_STREAMER_PROPERTIES_Lav_FILE_STREAMER_LOOPING:
        root::Lav_FILE_STREAMER_PROPERTIES = -2;
    pub const Lav_FILE_STREAMER_PROPERTIES_Lav_FILE_STREAMER_ENDED:
        root::Lav_FILE_STREAMER_PROPERTIES = -3;
    pub type Lav_FILE_STREAMER_PROPERTIES = i32;
    extern "C" {
        pub fn Lav_createEnvironmentNode(
            serverHandle: root::LavHandle,
            hrtfPath: *const ::std::os::raw::c_char,
            destination: *mut root::LavHandle,
        ) -> root::LavError;
    }
    extern "C" {
        pub fn Lav_environmentNodePlayAsync(
            nodeHandle: root::LavHandle,
            bufferHandle: root::LavHandle,
            x: f32,
            y: f32,
            z: f32,
            isDry: ::std::os::raw::c_int,
        ) -> root::LavError;
    }
    extern "C" {
        pub fn Lav_environmentNodeAddEffectSend(
            nodeHandle: root::LavHandle,
            channels: ::std::os::raw::c_int,
            isReverb: ::std::os::raw::c_int,
            connectByDefault: ::std::os::raw::c_int,
            destination: *mut ::std::os::raw::c_int,
        ) -> root::LavError;
    }
    extern "C" {
        pub fn Lav_createSourceNode(
            serverHandle: root::LavHandle,
            environmentHandle: root::LavHandle,
            destination: *mut root::LavHandle,
        ) -> root::LavError;
    }
    extern "C" {
        pub fn Lav_sourceNodeFeedEffect(
            nodeHandle: root::LavHandle,
            effect: ::std::os::raw::c_int,
        ) -> root::LavError;
    }
    extern "C" {
        pub fn Lav_sourceNodeStopFeedingEffect(
            nodeHandle: root::LavHandle,
            effect: ::std::os::raw::c_int,
        ) -> root::LavError;
    }
    extern "C" {
        pub fn Lav_sourceNodeSetPropertiesFromEnvironment(
            nodeHandle: root::LavHandle,
        ) -> root::LavError;
    }
    pub const lav_STANDARD_ENVIRONMENT_PROPERTIES_Lav_ENVIRONMENT_PANNING_STRATEGY:
        root::lav_STANDARD_ENVIRONMENT_PROPERTIES = 0;
    pub const lav_STANDARD_ENVIRONMENT_PROPERTIES_Lav_ENVIRONMENT_DISTANCE_MODEL:
        root::lav_STANDARD_ENVIRONMENT_PROPERTIES = 1;
    pub const lav_STANDARD_ENVIRONMENT_PROPERTIES_Lav_ENVIRONMENT_MAX_DISTANCE:
        root::lav_STANDARD_ENVIRONMENT_PROPERTIES = -12;
    pub const lav_STANDARD_ENVIRONMENT_PROPERTIES_Lav_ENVIRONMENT_DEFAULT_SIZE:
        root::lav_STANDARD_ENVIRONMENT_PROPERTIES = -11;
    pub const lav_STANDARD_ENVIRONMENT_PROPERTIES_Lav_ENVIRONMENT_OUTPUT_CHANNELS:
        root::lav_STANDARD_ENVIRONMENT_PROPERTIES = -10;
    pub const lav_STANDARD_ENVIRONMENT_PROPERTIES_Lav_ENVIRONMENT_REVERB_DISTANCE:
        root::lav_STANDARD_ENVIRONMENT_PROPERTIES = -9;
    pub const lav_STANDARD_ENVIRONMENT_PROPERTIES_Lav_ENVIRONMENT_MIN_REVERB_LEVEL:
        root::lav_STANDARD_ENVIRONMENT_PROPERTIES = -8;
    pub const lav_STANDARD_ENVIRONMENT_PROPERTIES_Lav_ENVIRONMENT_MAX_REVERB_LEVEL:
        root::lav_STANDARD_ENVIRONMENT_PROPERTIES = -7;
    pub const lav_STANDARD_ENVIRONMENT_PROPERTIES_Lav_ENVIRONMENT_POSITION:
        root::lav_STANDARD_ENVIRONMENT_PROPERTIES = -6;
    pub const lav_STANDARD_ENVIRONMENT_PROPERTIES_Lav_ENVIRONMENT_ORIENTATION:
        root::lav_STANDARD_ENVIRONMENT_PROPERTIES = -5;
    pub type lav_STANDARD_ENVIRONMENT_PROPERTIES = i32;
    pub const Lav_SOURCE_PROPERTIES_Lav_SOURCE_MAX_DISTANCE: root::Lav_SOURCE_PROPERTIES = 0;
    pub const Lav_SOURCE_PROPERTIES_Lav_SOURCE_DISTANCE_MODEL: root::Lav_SOURCE_PROPERTIES = 1;
    pub const Lav_SOURCE_PROPERTIES_Lav_SOURCE_SIZE: root::Lav_SOURCE_PROPERTIES = 2;
    pub const Lav_SOURCE_PROPERTIES_Lav_SOURCE_REVERB_DISTANCE: root::Lav_SOURCE_PROPERTIES = 3;
    pub const Lav_SOURCE_PROPERTIES_Lav_SOURCE_PANNING_STRATEGY: root::Lav_SOURCE_PROPERTIES = 4;
    pub const Lav_SOURCE_PROPERTIES_Lav_SOURCE_HEAD_RELATIVE: root::Lav_SOURCE_PROPERTIES = 5;
    pub const Lav_SOURCE_PROPERTIES_Lav_SOURCE_MIN_REVERB_LEVEL: root::Lav_SOURCE_PROPERTIES = 6;
    pub const Lav_SOURCE_PROPERTIES_Lav_SOURCE_MAX_REVERB_LEVEL: root::Lav_SOURCE_PROPERTIES = 7;
    pub const Lav_SOURCE_PROPERTIES_Lav_SOURCE_OCCLUSION: root::Lav_SOURCE_PROPERTIES = 8;
    pub const Lav_SOURCE_PROPERTIES_Lav_SOURCE_CONTROL_PANNING: root::Lav_SOURCE_PROPERTIES = 9;
    pub const Lav_SOURCE_PROPERTIES_Lav_SOURCE_CONTROL_DISTANCE_MODEL: root::Lav_SOURCE_PROPERTIES =
        10;
    pub const Lav_SOURCE_PROPERTIES_Lav_SOURCE_CONTROL_REVERB: root::Lav_SOURCE_PROPERTIES = 11;
    pub const Lav_SOURCE_PROPERTIES_Lav_SOURCE_POSITION: root::Lav_SOURCE_PROPERTIES = 12;
    pub const Lav_SOURCE_PROPERTIES_Lav_SOURCE_ORIENTATION: root::Lav_SOURCE_PROPERTIES = 13;
    pub type Lav_SOURCE_PROPERTIES = i32;
    pub const Lav_DISTANCE_MODELS_Lav_DISTANCE_MODEL_LINEAR: root::Lav_DISTANCE_MODELS = 0;
    pub const Lav_DISTANCE_MODELS_Lav_DISTANCE_MODEL_INVERSE: root::Lav_DISTANCE_MODELS = 1;
    pub const Lav_DISTANCE_MODELS_Lav_DISTANCE_MODEL_INVERSE_SQUARE: root::Lav_DISTANCE_MODELS = 2;
    pub type Lav_DISTANCE_MODELS = i32;
}
