//!
//! This crate was automatically generated by [`bindgen`](https://crates.io/crates/bindgen).
//!

#![allow(non_upper_case_globals)]
#![allow(non_camel_case_types)]
#![allow(non_snake_case)]

include!(concat!(env!("OUT_DIR"), "/bindings.rs"));

#[link(name = "libaudioverse")]

#[cfg(test)]
mod tests {
    use super::*;
    
    #[test]
    fn initializes_and_shuts_down() {
        unsafe {
            assert_eq!(Lav_initialize(), Lav_ERRORS_Lav_ERROR_NONE);
            assert_eq!(Lav_shutdown(), Lav_ERRORS_Lav_ERROR_NONE);
        }
    }
}
